### PR TITLE
Add CRD init to kustomize

### PR DESCRIPTION
**Pull request by vincent-pli**
The CRD `wedget` do not create after deployment, will raise 404 in log of controller

### CODE REVIEW

**Comment by ncdc** [comment]
/hold

This is not the right approach for kcp. I'll follow up more tomorrow.

**Comment by ncdc** [comment]
@vincent-pli how did you test your deployment?

**Comment by vincent-pli** [comment]
I installed the `controller` in my virtual cluster: root:gold:dogs
Then I get 404 exactly same as https://github.com/kcp-dev/kcp/issues/1183,
So I think it's caused by no CRD installed, so I installed the related CRD(widgets), then i get the error in #25 
That's all what I did, hope useful @ncdc

**Comment by ncdc** [comment]
You have to create an APIBinding for widgets somewhere, then it will work. I'm going to close this, but we can keep the conversation going if you'd like.

/close

**Pull request closed without merging**
